### ISSUE TITLE
Interface use case

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/qui-gon#1]
Need to admit I am fascinated by the code, but it seems I don't get the point. ;)

May be useful to define an interface?
Like in [ferrum](https://github.com/adobe/ferrum#traits-typeclasses)?

The following points are valid definitions (and from my point of view they are not expected, apart the first one):
```
const { struct: Point } = [{ i32: "x" }, { i32: "y" }];

const p1 = Point({ x: 0, y: 0 }); 
const p2 = Point({ x: 0, y: 0, z: 0 });
const p3 = Point({ x: 0 });  
```

Reading `to target WASM from a JS' subset`, maybe the goal it is like in [wasm-bindgen](https://rustwasm.github.io/wasm-bindgen/contributing/design/exporting-rust-struct.html).

Just my daily question. ;)

**Comment by WebReflection** [comment]
Apologies for the late answer, I really missed this notification!

> Need to admit I am fascinated by the code, but it seems I don't get the point. ;)

The point was to explore a syntax able to be transpiled into rust => WASM, keeping 100% JS compatibility.

This is ideally the typed version of asm.js

> May be useful to define an interface?

Definitions follow very closely Rust definitions, and I am not sure Rust has interfaces so ... structs are actually proper classes.

```js
const { struct: Point } = [{ i32: "x" }, { i32: "y" }];
```

Define a `Point` _struct_ defined through its fields, which are `x` and `y`, with their respective types.

The struct itself has no methods, just a list of defined fields.

Once a struct is defined, you can use it to expect those kind of variables in functions too, as in `fn({Point: xy})` and be sure `xy` is a `Point`.

> Reading to target WASM from a JS' subset, maybe the goal it is like in wasm-bindgen.

I don't think there's anything even similar to this idea out there, so I don't have projects to compare.

> Just my daily question. ;)

Hope I've answered. I'm also **not** actively working on this, but the idea that we could write modern JS and target WASM without needing any extra knowledge is some sort of dream that TypeScript or AssemblyScript would never be able to fulfill, for the simple reasons they don't natively work in JS while this project does already.
